config/routes.rb
Rails.application.routes.draw do

  resources :dpersonals do
    resources :dproductos
  end

  resources :dproductos do
    resources :solicituds
  end

  resources :laminas
  resources :inicio

  #get 'solicituds/createback'
  #post 'solicituds/createback'

  #get 'solicituds/destroyback'
  #post 'solicituds/destroyback'
    #resources :dpersonales, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dpersonal.rb
class Dpersonal < ApplicationRecord
  has_many :dproductos, dependent: :delete_all
  has_many :solicituds, through: :dproductos, dependent: :delete_all

  #ojo aqui es en plural, en el otro es en singular

  validates :cedula, presence: true
  validates :nombre, presence: true
  #validate :genero, presence: true
  validates :email, presence: true
  validates :pais, presence: true
  validates :departamento, presence: true
  validates :ciudad, presence: true
  validates :direccion, presence: true
end

app/models/dproducto.rb
class Dproducto < ApplicationRecord
  has_many :solicituds, dependent: :delete_all
  belongs_to :dpersonal

  #ojo aqui es en songular, en el otro es en plural
  validates	:cedula, presence: true
  validates	:poliza, presence: true
  validates	:valaseg, presence: true
  validates	:ciaaseg, presence: true
  validates	:estadoseg, presence: true
  validates	:pdtaseg, presence: true


end

app/models/lamina.rb
class Lamina < ApplicationRecord
#  belongs_to :solicitud
  #has_one :solicitud
  has_one_attached :photo


  validates :lamref, presence: true
  validates :lamnombre, presence: true
end

app/models/solicitud.rb
class Solicitud < ApplicationRecord
belongs_to :dproducto
has_many :laminas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dpersonals_controller.rb
class DpersonalsController < ApplicationController
  def index
    @dpersonals = Dpersonal.all
  end

  def new
    @dpersonal = Dpersonal.new
  end
  def create
    #render plain: params[:dpersonal].inspect
    @dpersonal = Dpersonal.new(dpersonal_permit)
      if @dpersonal.save
          redirect_to dpersonals_path
        else
          render 'new'
        end
  end

  def edit
      @dpersonal = Dpersonal.find(params[:id])
  end
  def update
    @dpersonal = Dpersonal.find(params[:id])
    if @dpersonal.update(dpersonal_permit)
      redirect_to @dpersonal
    else
      render :edit
    end
  end

  def show
    @dpersonal = Dpersonal.find(params[:id])

  end

    def destroy
      @dpersonal = Dpersonal.find(params[:id])
      @dpersonal.destroy
      redirect_to dpersonal_path
    end

  private
  def dpersonal_permit
    params.require(:dpersonal).permit(:cedula, :nombre, :genero, :email, :pais, :departamento, :ciudad, :direccion)
  end

end

app/controllers/dproductos_controller.rb
class DproductosController < ApplicationController
  def create
    @dpersonal = Dpersonal.find(params[:dpersonal_id])
    @dproducto = @dpersonal.dproductos.create(dproducto_params)
    redirect_to dpersonal_dproductos_path(@dpersonal)

  end
  def edit
    @dpersonal = Dpersonal.find(params[:dpersonal_id])
    @dproducto = @dpersonal.dproductos.find(params[:id])
      #redirect_to dpersonal_dproductos_path(@dpersonal)
  end

  def update
    @dpersonal = Dpersonal.find(params[:dpersonal_id])
    @dproducto = @dpersonal.dproductos.find(params[:id])
    if @dproducto.update(dproducto_params1)
      redirect_to dpersonal_dproductos_path(@dpersonal)
    else
      render :edit
    end
  end

  def destroy
    @dpersonal = Dpersonal.find(params[:dpersonal_id])
    @dproducto = @dpersonal.dproductos.find(params[:id])
    @dproducto.destroy
      redirect_to dpersonal_dproductos_path(@dpersonal)
  end

  def index
    @dpersonal = Dpersonal.find(params[:dpersonal_id])
    @dproductos = @dpersonal.dproductos.all
    #@dproducto = @dpersonal.dproductos.find(params[:id])
  end

  def show
    @dproducto = Dproducto.find(params[:id])
    @laminas = Lamina.all


    #@dpersonal = Dpersonal.find(params[:dpersonal_id])
    #@dproducto = @dpersonal.dproductos.find(params[:id])

  end

  private
    def dproducto_params
      params.require(:dproducto).permit([:cedula, :poliza, :valaseg, :ciaaseg, :estadoseg, :pdtaseg]
)
    end

    def dproducto_params1
      params.require(:dproducto).permit([:poliza, :valaseg, :ciaaseg, :estadoseg, :pdtaseg]
)
    end

end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index

       if params[:ced].present?
         @cedula = Dpersonal.find_by cedula: (params[:ced])
          if @cedula.present?
               redirect_to dpersonal_path(@cedula.id)
             else
               inicio_index_path
             end
        end


       if params[:adm].present?
         @adm = params[:adm]
               if @adm=='administrador'
                redirect_to dpersonals_path
                else
                inicio_index_path
                end
       end

    @cedu =  Dpersonal.all
   end
end

app/controllers/laminas_controller.rb
class LaminasController < ApplicationController
  def new
    @lamina = Lamina.new
  end

  def create
    #  render plain: params[:laminas].inspect
    #@lamina = Lamina.new(params[:lamina])
      @lamina = Lamina.create(lamina_permit)
        if @lamina.save
            redirect_to @lamina
          else
            render 'new'
          end
    end

    def show
      @lamina = Lamina.find(params[:id])
    end
    def index
      @laminas = Lamina.all
    end
    def edit
      @lamina = Lamina.find(params[:id])
    end
    def update
      @lamina = Lamina.find(params[:id])
      if @lamina.update(lamina_permit)
        redirect_to @lamina
      else
        render :edit
      end
    end

    def destroy
      @lamina = Lamina.find(params[:id])
      @lamina.destroy
      redirect_to lamina_path
    end


  private
  def lamina_permit
    params.require(:lamina).permit(:lamref, :lamnombre, :photo)
  end

end

app/controllers/solicituds_controller.rb
class SolicitudsController < ApplicationController
  def new
    @dproducto = Dproducto.find(params[:dproducto_id])
    #@solicitud = @dproducto.solicituds.new
    @solicitud = @dproducto.solicituds
    @laminas = Lamina.all
    #Carga el catalogo de láminas en new
    @personal = Dpersonal.find_by cedula: (@dproducto.cedula)
    #localiza el id de la cedula en dpersonal para link de volver al inicial del cliente
  end

  def create
    @dproducto = Dproducto.find(params[:dproducto_id])
    @solicitud = @dproducto.solicituds.create(solicitud_permit)

      redirect_to new_dproducto_solicitud_path(@dproducto)

  end

  def index
    @dproducto = Dproducto.find(params[:dproducto_id])
    @solicitud = @dproducto.solicituds
    @laminas = Lamina.all
    #Carga el catalogo de láminas en new
    @personal = Dpersonal.find_by cedula: (@dproducto.cedula)
    #localiza el id de la cedula en dpersonal para link de volve
  end

  def destroy
      @dproducto = Dproducto.find(params[:dproducto_id])
      @solicitud = @dproducto.solicituds.find(params[:id])
      @solicitud.destroy
       redirect_to new_dproducto_solicitud_path(@dproducto)

    end

  def show

  end

  def edit

  end

  def createback
    @dproducto = Dproducto.find(params[:dproducto_id])
    @solicitud = @dproducto.solicituds.create(solicitud_permit)
    redirect_to dproducto_solicituds_path(@dproducto)
  end

  def destroyback
    #@dproducto = Dproducto.find(params[:dproducto_id])
    @solicitud = Solicitud.find(params[:id])
    @solicitud.destroy
      redirect_to dproducto_solicituds_path(@dproducto)
  end


    private
    def solicitud_permit
    params.require(:solicitud).permit([:cedula, :lamref, :lamnombre, :carta, :empaque, :enviadoen])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dpersonals_helper.rb
module DpersonalsHelper
end

app/helpers/dproductos_helper.rb
module DproductosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/laminas_helper.rb
module LaminasHelper
end

app/helpers/solicituds_helper.rb
module SolicitudsHelper
end

app/views/dpersonals/_form.html.erb
<%= form_with model: @dpersonal do |f| %>

<% @dpersonal.errors.full_messages.each do |error|%>
<div>
<%= error %>
 </div>
<% end %>
<! #form_for :articulo, url: articulo_path(@articulo), method: :patch do |f| %>
<! OJO NO ES PATH ES PATCH Y NO ES articulos_path es articulo_path >
<% if @dpersonal.errors.any? %>
    <div id="error_explain">
      <h2>No se ha permitido guardar por:<%= pluralize @dpersonal.errors.count, 'error'%></h2>
        <ul>
          <% @dpersonal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
<% end %>

<div>
<%= f.label :cedula %>
<%= f.text_field :cedula %>
</div>
<div>
<%= f.label :nombre %>
<%= f.text_field :nombre %>
</div>
<div>
<%= f.label :genero %><br>
<%= f.radio_button :genero, "masculino"  %>Masculino<br>
<%= f.radio_button :genero, "femenino"  %>Femenino<br>
</div>
<div>
<%= f.label :email %>
<%= f.email_field  :email %>
</div>
<div>
<%= f.label :pais %>
<%= f.text_field  :pais %>
</div>
<div>
<%= f.label :departamento %>
<%= f.text_field  :departamento %>
</div>
<div>
<%= f.label :ciudad %>
<%= f.text_field  :ciudad %>
</div>
<div>
<%= f.label :direccion %>
<%= f.text_field  :direccion %>
</div>
<%= f.submit %>

<% end %>

app/views/dpersonals/edit.html.erb
<h1>Actualice sus Datos Personales</h1>
<p>Estos son sus datos personales por favor actualicelos si lo considera necesario:</p>
<%= render 'form' %>

<%= link_to 'Volver', dpersonal_path(@dpersonal) %>

app/views/dpersonals/index.html.erb
<h1>Dpersonals#index</h1>
<p>Find me in app/views/dpersonals/index.html.erb</p>
<%= link_to 'Nuevo Registro', new_dpersonal_path %>
<table>
<thead>
  <th>N</th>
  <th>Cedula</th>
  <th>Nombre</th>
  <th>Género</th>
  <th>Email</th>
  <th>País</th>
  <th>Departamento</th>
  <th>Ciudad</th>
  <th>Dirección</th>
  <th>Productos</th>
  <th>Actualizar</th>
</thead>
<tbody>
  <% @dpersonals.each do |dpersonal| %>
<tr>
  <th><%= dpersonal.id %></th>
  <th><%= dpersonal.cedula %></th>
  <th><%= dpersonal.nombre %></th>
  <th><%= dpersonal.genero %></th>
  <th><%= dpersonal.email %></th>
  <th><%= dpersonal.pais %></th>
  <th><%= dpersonal.departamento %></th>
  <th><%= dpersonal.ciudad %></th>
  <th><%= dpersonal.direccion %></th>
  <th><%= link_to 'Ver', dpersonal_dproductos_path(dpersonal) %></th>
  <th><%= link_to 'Actualizar', edit_dpersonal_path(dpersonal) %></th>
</tr>
  <% end %>
</tbody>
</table>
<h2><%= link_to 'Salir', inicio_index_path %></h2>

<p><h2> <%= link_to 'Administrar Catálogo de Láminas', laminas_path %></h2></p>

app/views/dpersonals/new.html.erb
<h1>Dpersonals#new</h1>
<p>Find me in app/views/dpersonals/new.html.erb</p>
<%= render 'form' %>

<%= link_to 'Volver', dpersonals_path %>
<a href="javascript:history.back()"> Volver Atrás</a>

app/views/dpersonals/show.html.erb
<h2>Datos Personales (Show)</h2>
<p>Estos son sus datos personales, por su seguridad manténgalos siempre actualizados</p>
<%#= link_to 'Inicio', dpersonals_path %>
<p>
<%= link_to 'Actualice sus Datos Personales', edit_dpersonal_path(@dpersonal) %>
<%#= link_to 'Eliminar', dpersonal_path(@dpersonal), data: {turbo_method: :delete, turbo_confirm: '¿Esta seguro?'} %>
</p>

ID: <%= @dpersonal.id %><br>
CEDULA: <%= @dpersonal.cedula %><br>
NOMBRE: <%= @dpersonal.nombre %><br>
GENERO: <%= @dpersonal.genero %><br>
EMAIL: <%= @dpersonal.email %><br>
PAIS: <%= @dpersonal.pais %><br>
DEPTO: <%= @dpersonal.departamento %><br>
CIUDAD: <%= @dpersonal.ciudad %><br>
DIRECCION: <%= @dpersonal.direccion %><br>

<h2>Productos del Cliente:</h2>
<%= render @dpersonal.dproductos %>

<%#= render 'dproductos/form' %>
<h2><%= link_to 'Salir', inicio_index_path %></h2>

app/views/dproductos/_dproducto.html.erb
<h3> Produto:</h3>
  ID: 	<b><%= dproducto.id%></b><br>
  CEDULA:	<b><%= dproducto.cedula%></b><br>
  N° DE POLIZA:	<b><%= dproducto.poliza%></b><br>
  VALOR DEL SEGURO:	<b><%= dproducto.valaseg%></b><br>
  AGENCIA ASEGURADORA:	<b><%= dproducto.ciaaseg%></b><br>
  ESTADO DEL SEGURO:	<b><%= dproducto.estadoseg%></b><br>
  PRODUCTO ASEGURADO:	<b><%= dproducto.pdtaseg%></b><br>
  <b><%=
    if (dproducto.estadoseg == "activo")
        if (dproducto.pdtaseg == "vida")
              link_to 'Este Seguro te Obsequia Láminas Educativas', new_dproducto_solicitud_path(dproducto)
        else
                '-'
        end
      end
    %></b><br>
  <%#= link_to 'Ver', dproducto_path(dproducto)%>
  <%#= link_to 'Editar', edit_dpersonal_dproducto_path(dproducto.dpersonal, dproducto) %>
  <%#= link_to 'Eliminar', [dproducto.dpersonal, dproducto], data: {turbo_method: :delete, turbo_confirm: '¿Esta seguro?'} %>

</p>

app/views/dproductos/_form.html.erb
<h2> Añadir o Editar Los Productos </h2>
<%#= form_for([@dpersonal, @dpersonal.dproductos.build]) do |f| %>
<%= form_with model: [@dpersonal, @dpersonal.dproductos.build] do |f| %>
<% @ced = @dpersonal.cedula%>
<div>
<%=	f.label :cedula	%>
<%= f.radio_button :cedula, @ced, :checked => true  %><%= @ced %>
<%#	f.text_field :cedula %>
</div>
<div>
<%=	f.label	:poliza	%>
<%=	f.text_field	:poliza	%>
</div>
<div>
<%=	f.label	:valaseg	%>
<%=	f.text_field	:valaseg	%>
</div>
<div>
<%=	f.label	:ciaaseg	%>
<%=	f.text_field	:ciaaseg	%>
</div>
<div>
<%=	f.label	:estadoseg	%>
<%#=	f.text_field	:estadoseg	%>
<%=	f.select(:estadoseg, options_for_select([['Activo','activo'],['Inactivo','inactivo']]), { include_blank: 'Seleccionar' })%>
</div>
<div>
<%=	f.label	:pdtaseg	%>
<%=	f.select(:pdtaseg, options_for_select([['Vida','vida'], ['Vehiculo','vehiculo'],['Hogar','hogar']]), { include_blank: 'Seleccionar' })%>
<%#=	f.text_field	:pdtaseg	%>
</div>
<%= f.submit "Guardar" %>
<% end %>

app/views/dproductos/edit.html.erb
<h1>Actualizar Datos del Seguro</h1>
<p>Estos son los datos del Seguro del Cliente, actualicelos si lo considera necesario:</p>
<%= form_with model: ([@dproducto.dpersonal, @dproducto]) do |f| %>

<% @ced = @dpersonal.cedula%>
<div>
<%=	f.label :cedula	%>
<%= f.radio_button :cedula, @ced, :checked => true  %><%= @ced %>
<div>
<%=	f.label	:poliza	%>
<%=	f.text_field	:poliza	%>
</div>
<div>
<%=	f.label	:valaseg	%>
<%=	f.text_field	:valaseg	%>
</div>
<div>
<%=	f.label	:ciaaseg	%>
<%=	f.text_field	:ciaaseg	%>
</div>
<div>
<%=	f.label	:estadoseg	%>
<%=	f.text_field	:estadoseg	%>
</div>
<div>
<%=	f.label	:pdtaseg	%>
<%=	f.text_field	:pdtaseg	%>
</div>
<%= f.submit 'Actaulizar'%>
<% end %>

app/views/dproductos/index.html.erb
<h1>Cliente:</h1>
<p>Estos son los datos personales del cliente</p>
ID: <%= @dpersonal.id %><br>
CEDULA: <%= @dpersonal.cedula %><br>
NOMBRE: <%= @dpersonal.nombre %><br>
GENERO: <%= @dpersonal.genero %><br>
EMAIL: <%= @dpersonal.email %><br>
PAIS: <%= @dpersonal.pais %><br>
DEPTO: <%= @dpersonal.departamento %><br>
CIUDAD: <%= @dpersonal.ciudad %><br>
DIRECCION: <%= @dpersonal.direccion %><br>

<h1>Productos:</h1>
<p>Estos son los productos personales del cliente</p>

<% @dproductos.each do |dproducto| %>
      <h3> Produto:</h3>
        ID: 	<b><%= dproducto.id%></b><br>
        CEDULA:	<b><%= dproducto.cedula%></b><br>
        N° DE POLIZA:	<b><%= dproducto.poliza%></b><br>
        VALOR DEL SEGURO:	<b><%= dproducto.valaseg%></b><br>
        AGENCIA ASEGURADORA:	<b><%= dproducto.ciaaseg%></b><br>
        ESTADO DEL SEGURO:	<b><%= dproducto.estadoseg%></b><br>
        PRODUCTO ASEGURADO:	<b><%= dproducto.pdtaseg%></b><br>
        <b><%=
          if (dproducto.estadoseg == "activo")
              if (dproducto.pdtaseg == "vida")
                    link_to 'Láminas Solicitadas por el Cliente>>', new_dproducto_solicitud_path(dproducto, :md => "1")
              else
                      '-'
              end
            end
          %></b><br>
        <%= link_to 'Ver', dproducto_path(dproducto)%>
        <%= link_to 'Editar', edit_dpersonal_dproducto_path(dproducto.dpersonal, dproducto) %>
        <%= link_to 'Eliminar', [dproducto.dpersonal, dproducto], data: {turbo_method: :delete, turbo_confirm: '¿Esta seguro?'} %>
    <% end %>
<%#= render @dpersonal.dproductos %>

<%= render 'dproductos/form' %>
<h2>
<%= link_to 'Inicio', dpersonals_path %>
</h2>
<h2><%= link_to 'Salir', inicio_index_path %></h2>

app/views/dproductos/show.html.erb
<h1>Dproductos#show</h1>
<p>Find me in app/views/dproductos/show.html.erb</p>

  ID: 	<%= @dproducto.id%><br>
  CEDULA:	<%= @dproducto.cedula%><br>
  POLIZA:	<%= @dproducto.poliza%><br>
  VALASEG:	<%= @dproducto.valaseg%><br>
  CIAASEG:	<%= @dproducto.ciaaseg%><br>
  ESTADOSEG:	<%= @dproducto.estadoseg%><br>
  PDTASEG:	<%= @dproducto.pdtaseg%><br>
  <%= link_to 'Editar', edit_dpersonal_dproducto_path(@dproducto.dpersonal, @dproducto) %><br>
  <%#= link_to 'Eliminar', [@dproducto.dpersonal, @dproducto], data: {turbo_method: :delete, turbo_confirm: '¿Esta seguro?'} %>
  <a href="javascript:history.back()"> Volver Atrás</a>
  </p>

app/views/inicio/index.html.erb
<h1>Módulo de Consulta de Productos</h1>
<h2> Cliente - Bienvenido </h2>
<div>
<p>
  Usted se encuentra en nuestro módulo de consulta de productos,<br>
  Por favor ingrese su <b>número de cédula</b> para consultar sus datos y productos:
</p>
<p>
  <%= form_tag inicio_index_path, method: :get do %>
    <%= text_field_tag :ced, params[:ced], placeholder: "Cedula del Cliente" %>
    <%= submit_tag "Buscar", name: nil %>
  <% end %>
</p>
</div>
<br>
<br>

<div>
<h2> Administrador - Bienvenido </h2>
<p>
    Si usted hace parte del área administrativa, por favor ingrese su contraseña: => <b>(administrador)</b>:

  <%= form_tag inicio_index_path, method: :get do %>
    <%= text_field_tag :adm, params[:adm], placeholder: "Pass - Administrador" %>
    <%= submit_tag "Buscar", name: nil %>
  <% end %>
</p>
  </div>
<b>IMPORTANTE:</b> Este es un sistema para una empresa Corredora de Seguros que desea
mantener informado a sus clientes sobre los Productos que adquirieron con la empresa
y el estado en que se encuentra el producto.<br>
Además pretende hacer un reconocimiento por el producto adquirido; en este caso se permite a los <b>Educadores</b> que poseen un <b>seguro de Vida</b>, solicitar
una(1) <b>Lámina Educativa</b> por cada 10 millones de <b>Valor asegurado</b>.
<br><br>
En el Inicio, se podrá observar un espacio para el <b>Cliente</b> y otro para el <b>Administrador del sistema</b>
<br>
<br>
Para probar el sistema, pruebe con las siguientes identificaciones:
<br>
<% @cedu.each do |cedu| %>
  <%= cedu.cedula %><br>
    <% end %>

<%
if @cedula.present?
@cedula.id
end
%>

app/views/laminas/edit.html.erb
<h1>Laminas#Edit</h1>
<p>Sistema de actualización de Láminas ducativas con imagen</p>
<%= form_with model: @lamina do |form| %>
<% #form_with model: @lamina, url: lamina_path do |form| %>
<% #form_with model: @lamina, url: '/laminas/:id' do |form| %>

  <div>
  <%= form.label :Ref %>
  <%= form.text_field :lamref %>
  </div>
  <div>
  <%= form.label :Nombre %>
  <%= form.text_field :lamnombre %>
  </div>
  <div>
  <%= form.label :Imagen %>
  <%= form.file_field :photo %>
  </div>
  <%= form.submit %>
<% end %>

app/views/laminas/index.html.erb
<h1>ADMINISTRACIÓN DE CATALOGO DE LÁMINAS EDUCATIVAS</H1>
<p><H3><%= link_to 'Insertar Nueva Lámina', new_lamina_path  %></H3></p>


<table border="1">
  <thead>
      <tr>
        <th>Código</th>
        <th>Titulo</th>
        <th>Imagen</th>
        <th>Actualizar</th>
        <th>Borrar</th>

      </tr>
      </thead>
    <tbody>
      <% @laminas.each do |lamina| %>
      <tr>
        <th><%= lamina.lamref  %></th>
        <th><%= lamina.lamnombre  %></th>
        <th><%= image_tag lamina.photo, width: 200 if lamina.photo.attached? %></th>
        <th><%= link_to 'Editar Lamina', edit_lamina_path(lamina)  %></th>
        <th><%= link_to 'Eliminar', lamina_path(lamina), data: {turbo_method: :delete, turbo_confirm: '¿Esta seguro?'} %></th>

      </tr>
      <% end %>
    </tbody>
  </table>

<p><H3><%= link_to 'Salir', inicio_index_path  %></H3></p>

app/views/laminas/new.html.erb
<h1>Laminas#New</h1>
<p>Sistema de carga de láminas Educativas con imagen</p>
<%#= form_with model: @lamina do |form| %>
<%= form_with model: @lamina, url: laminas_path do |form| %>
<%#= form_for laminas_path do |form| %>

  <div>
  <%= form.label :Ref %>
  <%= form.text_field :lamref %>
  </div>
  <div>
  <%= form.label :Nombre %>
  <%= form.text_field :lamnombre %>
  </div>
  <div>
  <%= form.label :Imagen %>
  <%= form.file_field :photo %>
  </div>
  <%= form.submit %>
<% end %>


<p>   <H3>
<%= link_to 'Inicio Láminas', laminas_path  %></H3></p>

app/views/laminas/show.html.erb
<H2>LAMINA EDUCATIVA</H2>
<H3><%= @lamina.lamnombre  %></H3>
<%= image_tag @lamina.photo if @lamina.photo.attached? %>

<p>   <H3><%= @lamina.lamref  %></H3></p>
<%= link_to 'Editar Lamina', edit_lamina_path(@lamina)  %>

<p>   <H3>
<%= link_to 'Inicio Láminas', laminas_path  %></H3></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laminas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <font color="black" face="arial narrow">
    <%= yield %>
    </font>
  </body>
</html>

app/views/solicituds/_form.html.erb
<%= render 'laminassel' %>
<h2>Catálogo de Láminas</h2>
<%#= @conta %>
<%#= @valaseg%>
  <%=
      if (@conta>=@valaseg)
      "Usted ha completado su solicitud de Láminas Educativas<br>".html_safe+
      "Su Obsequio será enviado a la dirección:<br>".html_safe+
      @personal.direccion+" de la ciudad de: "+@personal.ciudad
      end
  %>

<%=
#Este hash esconde la tabla cuando se completo la solicitud
  if (@conta>=@valaseg)
      "<div hidden>".html_safe
  end
%>
<table border="1">
  <thead>
      <tr>
        <th>Cédula</th>
        <th>Código</th>
        <th>Título</th>
        <th>Imagen</th>
        <th>Escoger</th>
      </tr>
      </thead>
    <tbody>
        <% @laminas.each do |lamina| %>
          <tr>
            <%= form_with model: [@dproducto, @dproducto.solicituds.build] do |f| %>

            <th>
              <%=	f.label @ced	%><br>
              <%= f.text_field :cedula,value: @ced %><br>
              <%#= f.radio_button :cedula, @ced, :checked => true  %><br>
            </th>

            <th>
              <%= f.label lamina.lamref  %><br>
              <%= f.text_field :lamref,value: lamina.lamref %><br>
              <%#= f.radio_button :lamref, lamina.lamref, :checked => true  %>
            </th>

            <th>
              <%= f.label lamina.lamnombre  %><br>
              <%= f.text_field :lamnombre,value: lamina.lamnombre %><br>
              <%#= f.radio_button :lamnombre, lamina.lamnombre, :checked => true  %>
            </th>

            <th>
              <%= image_tag lamina.photo, width: 200 if lamina.photo.attached? %>
            </th>

            <th>
              <%= f.submit "Seleccionar" %>
            </th>
              <% end %>
          </tr>

        <% end %>

    </tbody>
  </table>
  <%=
  #Este hash esconde la tabla cuando se completo la solicitud
    if (@conta>=@valaseg)
        "</div>".html_safe
    end
  %>

app/views/solicituds/edit.html.erb
<h1>Solicituds#edit</h1>
<p>Find me in app/views/solicituds/edit.html.erb</p>

app/views/solicituds/show.html.erb
<h1>Solicituds#show</h1>
<p>Find me in app/views/solicituds/show.html.erb</p>

<h2>Productos del Cliente:</h2>
<%= render  @dproducto.solicituds %>